# -*- coding: utf-8 -*-
"""capstone_ultralytics_yolo11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOnM_50swNRERROffV0Om_P8GPri_FBx

#**Computer Vision for Developers with Ultralytics — SDAIA Academy**

**🧠 Brain-Tumor Detection & Automated tumor counting on MRI scans. — YOLO11 Capstone**

##**Setup**
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q -U ultralytics onnx onnxruntime

import ultralytics, torch
ultralytics.checks()
print("Torch CUDA available:", torch.cuda.is_available())
print("Device:", "GPU (T4)" if torch.cuda.is_available() else "CPU  ⚠️  T4 GPU - Runtime")

"""##  Custom Data & Training

"""

from ultralytics import YOLO

train_model = YOLO("yolo11n.pt")

train_results = train_model.train(
    data="brain-tumor.yaml",
    epochs=30,
    imgsz=640,
    batch=16,
    patience=15,
    seed=0,
    plots=True,
    project="runs",
    name="brain_tumor_yolo11n",
    exist_ok=True,
)

from pathlib import Path
run_dir  = Path(train_results.save_dir)
best_pt  = run_dir / "weights" / "best.pt"
print("Training finished. Best weights:", best_pt)

# Display training curves + confusion matrix (execution evidence; check over/underfitting)
import matplotlib.pyplot as plt

for img_name in ["results.png", "confusion_matrix.png"]:
    p = run_dir / img_name
    if p.exists():
        plt.figure(figsize=(12, 7))
        plt.imshow(plt.imread(str(p))); plt.axis("off")
        plt.title(img_name); plt.show()
    else:
        print("Not found:", p)

"""**Reading the result (over/underfitting):** All `train/*_loss` curves keep decreasing steadily through epoch 26 without flattening, and `val/*_loss` also trends down (after early noise) rather than rising — so there is no overfitting; if anything the model is slightly underfitting and could still improve with more training. Early-stopping halted at epoch 26. Accuracy is modest and expected: `yolo11n` is small and the dataset is limited. To improve it I would train longer or move to a larger model (`yolo11s`) with stronger augmentation.

##  Core Vision Tasks & Inference

Running inference on MRI scans:
- **Detection** — the trained `best.pt` draws boxes around tumors (finds *where* they are).
- **Instance Segmentation** (a task beyond detection) — `yolo11n-seg.pt` outlines objects pixel-by-pixel, not just boxes. It's a general (non-medical) model, so `Masks found: 0` on MRI is expected; the point is to show the segmentation task runs.
"""

import glob, os


try:
    from ultralytics.data.utils import check_det_dataset
    dd = check_det_dataset("brain-tumor.yaml")
    vp = dd["val"]
    vp = vp[0] if isinstance(vp, (list, tuple)) else vp
    vp = Path(vp)
    if vp.is_file():
        mri_images = [l.strip() for l in open(vp) if l.strip()]
    else:
        mri_images = sorted(glob.glob(str(vp / "*.jpg")) + glob.glob(str(vp / "*.png")))
except Exception as e:
    print("path lookup fell back to glob:", e)
    mri_images = sorted(g for g in glob.glob("/content/datasets/brain-tumor/**/*.jpg",
                                             recursive=True) if "val" in g.lower())

print("Found", len(mri_images), "validation MRI scans")
sample_img = mri_images[0]
print("Sample:", sample_img)

# --- Detection with the trained brain-tumor model ---
det_model = YOLO(str(best_pt))
det_res = det_model.predict(source=sample_img, save=True, conf=0.25, imgsz=640)
dr = det_res[0]

print("Tumor detections in this scan:", 0 if dr.boxes is None else len(dr.boxes))
for b in (dr.boxes or []):
    print(f"  - {det_model.names[int(b.cls)]:10s} conf={float(b.conf):.2f}")

plt.figure(figsize=(8, 8))
plt.imshow(dr.plot()[..., ::-1])   # BGR -> RGB
plt.axis("off"); plt.title("YOLO11 — Brain-Tumor Detection (trained model)"); plt.show()

## --- Instance Segmentation: a task beyond detection (task-specific weights) ---
seg_model = YOLO("yolo11n-seg.pt")
seg_res = seg_model.predict(source=sample_img, save=True, imgsz=640)
sr = seg_res[0]

print("Segmentation task ran. Masks found:", 0 if sr.masks is None else len(sr.masks))
plt.figure(figsize=(8, 8))
plt.imshow(sr.plot()[..., ::-1])
plt.axis("off"); plt.title("YOLO11 — Instance Segmentation task on MRI"); plt.show()

"""##  Real-World Solution & Video Analytics

Automated Screening: a real OpenCV pipeline runs model.track over an MRI image stream, writing an output video and counting tumors per scan and overall.

"""

import cv2

SIZE = 640
FPS  = 5
stream = mri_images[:40]

screener = YOLO(str(best_pt))
writer = cv2.VideoWriter("screening_stream.mp4",
                         cv2.VideoWriter_fourcc(*"mp4v"), FPS, (SIZE, SIZE))

per_scan_counts, total_detections, samples = [], 0, []
for idx, ip in enumerate(stream):
    img = cv2.imread(ip)
    if img is None:
        continue
    img = cv2.resize(img, (SIZE, SIZE))
    res = screener.track(img, persist=True, conf=0.25, verbose=False)
    n = 0 if res[0].boxes is None else len(res[0].boxes)
    per_scan_counts.append(n); total_detections += n

    annotated = res[0].plot()
    cv2.putText(annotated,
                f"scan {idx+1}/{len(stream)}  this scan: {n}  total: {total_detections}",
                (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
    writer.write(annotated)
    if idx in (0, len(stream) // 2):
        samples.append(annotated.copy())

writer.release()
flagged = sum(1 for c in per_scan_counts if c > 0)
print(f"Screened {len(per_scan_counts)} MRI scans")
print(f"Scans flagged (>=1 detection): {flagged}")
print(f"Total tumor detections across the stream: {total_detections}")
print("Saved annotated screening video -> screening_stream.mp4")

# عرض عيّنة إطارات inline
for s in samples:
    plt.figure(figsize=(8, 8))
    plt.imshow(s[..., ::-1]); plt.axis("off")
    plt.title("Automated screening pipeline (model.track over MRI stream)"); plt.show()

import subprocess, os
from IPython.display import HTML
from base64 import b64encode


subprocess.run(
    ["ffmpeg", "-y", "-i", "screening_stream.mp4",
     "-vcodec", "libx264", "-pix_fmt", "yuv420p", "screening_play.mp4"],
    capture_output=True
)

show = "screening_play.mp4" if os.path.exists("screening_play.mp4") else "screening_stream.mp4"
mp4 = open(show, "rb").read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML(f'<video width=500 controls><source src="{data_url}" type="video/mp4"></video>')

"""##  Model Evaluation


"""

best = YOLO(str(best_pt))
metrics = best.val(data="brain-tumor.yaml", imgsz=640, conf=0.25, iou=0.6, plots=True)

print("=== Validation metrics (Brain-Tumor) ===")
print(f"mAP50-95 : {float(metrics.box.map):.4f}")
print(f"mAP50    : {float(metrics.box.map50):.4f}")
print(f"mAP75    : {float(metrics.box.map75):.4f}")
print(f"Precision: {float(metrics.box.mp):.4f}")
print(f"Recall   : {float(metrics.box.mr):.4f}")

"""### Interpretation (medical context)


- **mAP50 / mAP50-95** — detection accuracy at IoU 0.50, and averaged over IoU 0.50–0.95 (stricter, penalizes loose tumor localization).
- **Precision (0.47)** — of all "tumor" predictions, how many were correct. Low precision means **false positives (FP)** — extra alarms.
- **Recall (0.80)** — of all real tumors, how many the model caught. Low recall means **false negatives (FN)** — missed tumors.
- **In medical screening, a false negative (missing a tumor) is far more costly than a false positive** (an extra alarm a radiologist reviews). Our model already favors this trade-off: **Recall (0.80) > Precision (0.47)** — it is sensitive and catches most tumors at the cost of some false alarms, which is the right balance for a triage system. To push sensitivity further, lower the `conf` threshold (e.g. 0.15 instead of 0.25) with expert review of uncertain cases.
- **Confusion Matrix** — off-diagonal cells are errors. Most confusion is in the `positive` class (real tumors predicted as background), i.e. the **FN** we most want to reduce.
- **IoU = 0.6** was chosen for validation as a balance: high enough to require good localization, not so strict that minor box differences are penalized.

##  Deployment & Export

Export the trained model to **ONNX** and verify it runs with `onnxruntime`. ONNX is portable and runs on CPU without PyTorch/GPU.
"""

onnx_path = best.export(format="onnx", imgsz=640, opset=12)
print("Exported ONNX model ->", onnx_path)

import onnxruntime as ort
sess = ort.InferenceSession(onnx_path, providers=["CPUExecutionProvider"])
print("ONNX runtime session OK")
print("Inputs :", [i.name for i in sess.get_inputs()])
print("Outputs:", [o.name for o in sess.get_outputs()])